#!/bin/bash

xargs -I {} grep -oHE ' [a-z][a-z\_A-Z0-9]{4,}\(' {} | awk -F': ' '{print $2}' | sed 's/(//g' | sort --uniq | grep -v -E 'str.+|pthread|free|abort|.*alloc|mem.+|.*[Pp]rint|[Ss]leep|assert|while|sizeof'
