#!/bin/bash
DIRNAME=$(dirname $(realpath $0))
printf "set height 0\nset logging on\nset logging redirect on\n\n"

$DIRNAME/showfn | xargs -I {} printf "break {}\ncommand\nsilent\nbacktrace 2\ncontinue\nend\n\n"
