#!/bin/bash
DIRNAME=$(dirname $(realpath $0))
printf "set height 0\nset logging on\nset logging overwrite on\nset logging redirect on\n\n"

xargs -I {} printf "break {}\ncommand\nsilent\nbacktrace\ncontinue\nend\n\n"

